### ISSUE TITLE
it literally wont work

### ISSUE THREAD

**Issue by AllMesi** [john32b/djFlixel#14]
```
source/Game.hx:13: characters 8-18 : Type not found : djFlixel.D
source/Game.hx:14: characters 8-35 : Type not found : djFlixel.gfx.RainbowStripes
source/Game.hx:15: characters 8-32 : Type not found : djFlixel.other.DelayCall
source/Game.hx:43: characters 3-4 : Type not found : D
source/Game.hx:48: characters 3-4 : Type not found : D
source/Game.hx:49: characters 3-4 : Type not found : D
source/Game.hx:50: characters 3-4 : Type not found : D
source/Game.hx:51: characters 3-4 : Type not found : D
source/Game.hx:80: characters 3-4 : Type not found : D
```

it wont find anything
no more info for now

**Comment by AllMesi** [comment]
i installed it with `haxelib git djFlixel https://github.com/john32b/djFlixel.git`

**Comment by john32b** [comment]
Hey,

Hmm, it's been some time since I looked at this project. Yes, there is an error in the installation line of the library, it should be: `haxelib git djFlixel https://github.com/john32b/djFlixel` ... I will update the docs later.

I did a fresh install using the git command on my system and it works.  Try ::

- Use latest everything, Haxe 4.2.4, flixel 4.11, openfl 9.1.0, lime 7.9.0.
- Make sure it downloaded and the folder `C:\HaxeToolkit\haxe\lib\djFlixel\git\` is populated with the project files
- Try compiling the demo project to flash or hashlink
    - Go to `C:\HaxeToolkit\haxe\lib\djFlixel\git\demo` or wherever the project files are
    - The demo runs best in hashlink (haven't tried native c++ to tell the truth)
    - Do a  `lime build hl -debug`. That should build a hashlink binary in the `/bin` folder.

I don't remember but lime might complain about HL not being setup? To get HL running:
  - Get hashlink from https://github.com/HaxeFoundation/hashlink/releases
  - Extract it somewhere and do a `lime setup hl`
  - It will ask you to download it, press n for no
  - Tell it the path where you installed it to

**Comment by AllMesi** [comment]
so
on another project my ide or hashlink cant find anything
BUT 
the demo works????

any ideas?

**Comment by AllMesi** [comment]
ive tested for windows and neko
neko just doesnt work
windows works but the static thing in the beginning isnt there

**Comment by AllMesi** [comment]
OH WAIT I KNOW WHY IT WONT WORK

i forgot to import the thing in project.xml
im such an idiot

**Comment by john32b** [comment]
dude 😅😆😆
glad you got it running.

also, give a try to HashLink instead of Neko . I think neko is dead at this point.
